(in-package #:asdf-user)

(asdf:defsystem "cl-postgresql-kit"
  :description "A PostgreSQL wire-protocol client for Common Lisp."
  :version "1.0.0"
  :license "MIT"
  :depends-on ((:version "cl-codec-kit" "0.5.0")
               (:version "cl-json-kit" "1.2.0")
               (:version "cl-date-kit" "1.0.0")
               (:version "cl-concurrent-kit" "0.6.1")
               (:version "cl-log-kit" "2.2.0")
               (:version "cl-observability-kit" "0.1.0")
               (:version "cl-resilience-kit" "1.0.0"))
  :pathname "src"
  :serial t
  :components ((:file "package")
               (:file "conditions")
               (:file "wire")
               (:file "crypto")
               (:file "transport")
               (:file "transport-socket")
               (:file "transport-memory")
               (:file "protocol-encode")
               (:file "protocol-response")
               (:file "protocol-response-startup")
               (:file "protocol-replication")
               (:file "protocol-replication-logical-data")
               (:file "protocol-replication-logical-row")
               (:file "protocol-replication-logical")
               (:file "types-data")
               (:file "types")
               (:file "codecs-primitives")
               (:file "codecs-numeric")
               (:file "codecs-builtin")
               (:file "codecs-network")
               (:file "codecs-network-address")
               (:file "codecs-binary")
               (:file "codecs-json-uuid")
               (:file "types-temporal")
               (:file "types-temporal-text")
               (:file "types-temporal-binary")
               (:file "types-collections")
               (:file "types-collections-array")
               (:file "types-collections-array-text")
               (:file "types-collections-array-binary")
               (:file "types-structured-text")
               (:file "types-structured-range")
               (:file "types-structured-composite")
               (:file "types-registration")
               (:file "types-registration-builtins")
               (:file "connection-data")
               (:file "query-result")
               (:file "observability")
               (:file "connection-string-parse")
               (:file "connection-string-libpq")
               (:file "connection-string-options")
               (:file "connection-build")
               (:file "connection-string-uri")
               (:file "auth-crypto")
               (:file "auth-protocol")
               (:file "auth-methods-scram")
               (:file "auth-methods-oauth")
               (:file "auth-methods")
               (:file "connection-startup-tls")
               (:file "connection-startup-session")
               (:file "connection-startup")
               (:file "connection")
               (:file "query-parameters")
               (:file "query-execution-frames")
               (:file "query-execution-data")
               (:file "query-execution-results")
               (:file "query-execution")
               (:file "cursor")
               (:file "query-timeout")
               (:file "operation")
               (:file "query")
               (:file "query-prepared")
               (:file "query-pipeline-build")
               (:file "query-pipeline-results")
               (:file "query-pipeline")
               (:file "type-registry")
               (:file "advanced-operations-data")
               (:file "advanced-operations")
               (:file "large-object-data")
               (:file "large-object")
               (:file "pool-data")
               (:file "pool")
               (:file "copy-codecs")
               (:file "copy-codecs-row-binary")
               (:file "copy-codecs-text-stream")
               (:file "copy-codecs-binary")
               (:file "copy-session")
               (:file "copy-session-read")
               (:file "replication-sql")
               (:file "replication-sql-base-backup")
               (:file "replication-base-backup-results")
               (:file "replication-base-backup")
               (:file "replication")
               (:file "logical-replication")
               (:file "logical-replication-events")
               (:file "logical-replication-events-stream"))
  :in-order-to ((test-op (test-op "cl-postgresql-kit/test"))))

(asdf:defsystem "cl-postgresql-kit/test"
  :description "Protocol and client tests for cl-postgresql-kit."
  :depends-on ("cl-postgresql-kit"
               (:version "cl-weave" "1.3.0"))
  :pathname "t"
  :serial t
  :components ((:file "package")
               (:file "support")
               (:file "support-wire")
               (:file "support-fixtures")
               (:file "crypto-tests")
               (:file "protocol-data-tests")
               (:file "floating-point-codec-tests")
               (:file "numeric-codec-tests")
               (:file "protocol-wire-tests")
               (:file "protocol-codec-array-tests")
               (:file "network-codec-tests")
               (:file "type-registry-tests")
               (:file "type-registry-boundary-tests")
               (:file "protocol-range-codec-tests")
               (:file "protocol-structured-codec-tests")
               (:file "protocol-codec-tests")
               (:file "temporal-binary-codec-tests")
               (:file "protocol-condition-tests")
               (:file "protocol-tests")
               (:file "protocol-frame-tests")
               (:file "protocol-validation-tests")
               (:file "protocol-response-tests")
               (:file "temporal-codec-property-tests")
               (:file "function-call-tests")
               (:file "transport-tests")
               (:file "connection-string-tests")
               (:file "connection-startup-tests")
               (:file "connection-configuration-tests")
               (:file "connection-runtime-tests")
               (:file "connection-tests")
               (:file "connection-auth-tests")
               (:file "connection-auth-sasl-tests")
               (:file "connection-auth-oauth-tests")
               (:file "notification-tests")
               (:file "data-tests")
               (:file "query-pipeline-tests")
               (:file "query-result-collection-tests")
               (:file "query-execution-tests")
               (:file "query-tests")
               (:file "pool-tests")
               (:file "copy-tests")
               (:file "large-object-tests")
               (:file "logical-replication-tests")
               (:file "logical-replication-message-codec-tests")
               (:file "logical-replication-codecs-tests")
               (:file "logical-replication-decoder-tests")
               (:file "replication-command-tests")
               (:file "replication-tests")
               (:file "runner"))
  :perform (asdf:test-op (operation component)
             (declare (ignore operation component))
             (uiop:symbol-call '#:cl-postgresql-kit/test '#:run-tests)))

;; TLS stays optional because the portable/core client has no dependency on a
;; foreign SSL library.  Loading this system adds the CL+SSL transport method.
(asdf:defsystem "cl-postgresql-kit/tls"
  :description "TLS transport support for cl-postgresql-kit."
  :depends-on ("cl-postgresql-kit" "cl+ssl")
  :pathname "src"
  :components ((:file "tls")))
