(defpackage #:cl-postgresql-kit
  (:use #:cl)
  (:shadow #:listen)
  (:export
   ;; Conditions
   #:postgresql-condition
   #:postgresql-condition-message
   #:postgresql-error
   #:protocol-error
   #:protocol-error-context
   #:protocol-error-expected
   #:protocol-error-actual
   #:transport-error
   #:transport-error-operation
   #:transport-error-cause
   #:connection-error
   #:authentication-error
   #:oauth-discovery-required
   #:oauth-discovery-response
   #:oauth-discovery-server-fields
   #:query-error
   #:multiple-results-error
   #:timeout-error
   #:timeout-error-cancel-sent-p
   #:timeout-error-connection-retired-p
   #:tls-error
   #:tls-error-cause
   #:pool-error
   #:pool-exhausted
   #:pool-exhausted-timeout
   #:transaction-error
   #:copy-error
   #:unsupported-feature
   #:unsupported-feature-name
   #:parameter-error
   #:parameter-error-parameter
   #:server-error
   #:server-error-fields
   #:server-error-severity
   #:server-error-sqlstate
   #:server-error-message
   #:server-error-detail
   #:server-error-hint
   #:server-error-position
   #:server-error-where
   #:server-error-schema
   #:server-error-table
   #:server-error-column
   #:server-error-datatype
   #:server-error-constraint
   #:server-error-file
   #:server-error-line
   #:server-error-routine
   #:server-error-unknown-fields
   #:notice
   #:notice-fields
   ;; Wire helpers
   #:make-octet-builder
   #:octet-builder-p
   #:builder-octets
   #:append-octets
   #:append-u8
   #:append-i16
   #:append-u16
   #:append-i32
   #:append-u32
   #:append-u64
   #:append-i64
   #:append-cstring
   #:make-frame
   #:read-backend-message
   #:backend-message
   #:backend-message-p
   #:backend-message-type
   #:backend-message-payload
   #:parse-frame
   #:*maximum-frame-size*
   ;; Protocol encoders/parsers
   #:+protocol-version-3.0+
   #:+protocol-version-3.2+
   #:encode-startup-message
   #:encode-ssl-request
   #:encode-gssenc-request
   #:encode-cancel-request
   #:encode-query-message
   #:encode-parse-message
   #:encode-bind-message
   #:encode-describe-message
   #:encode-execute-message
   #:encode-flush-message
   #:encode-function-call-message
   #:encode-close-message
   #:encode-sync-message
   #:encode-terminate-message
   #:encode-password-message
   #:encode-sasl-initial-response
   #:encode-sasl-response
   #:encode-gss-response
   #:encode-copy-data-message
   #:encode-copy-done-message
   #:encode-copy-fail-message
   #:parse-authentication
   #:parse-parameter-status
   #:parse-backend-key-data
   #:parse-negotiate-protocol-version
   #:parse-ready-for-query
   #:parse-row-description
   #:parse-data-row
   #:parse-command-complete
   #:parse-error-response
   #:parse-notification-response
   #:parse-copy-response
   #:parse-copy-data
   #:replication-message
   #:replication-message-p
   #:replication-message-kind
   #:replication-message-wal-start
   #:replication-message-wal-end
   #:replication-message-send-time
   #:replication-message-reply-requested
   #:replication-message-data
   #:replication-message-client-time
   #:replication-message-write-lsn
   #:replication-message-flush-lsn
   #:replication-message-apply-lsn
   #:replication-message-xmin
   #:replication-message-xmin-epoch
   #:replication-message-catalog-xmin
   #:replication-message-catalog-xmin-epoch
   #:parse-replication-message
   #:base-backup-message
   #:base-backup-message-p
   #:base-backup-message-kind
   #:base-backup-message-archive-name
   #:base-backup-message-tablespace-path
   #:base-backup-message-data
   #:base-backup-message-bytes-completed
   #:parse-base-backup-message
   #:logical-replication-field
   #:logical-replication-field-p
   #:logical-replication-field-kind
   #:logical-replication-field-data
   #:logical-replication-tuple
   #:logical-replication-tuple-p
   #:logical-replication-tuple-fields
   #:logical-replication-column
   #:logical-replication-column-p
   #:logical-replication-column-flags
   #:logical-replication-column-name
   #:logical-replication-column-type-oid
   #:logical-replication-column-type-modifier
   #:logical-replication-message
   #:logical-replication-message-p
   #:logical-replication-message-kind
   #:logical-replication-message-protocol-version
   #:logical-replication-message-xid
   #:logical-replication-message-final-lsn
   #:logical-replication-message-commit-lsn
   #:logical-replication-message-end-lsn
   #:logical-replication-message-commit-time
   #:logical-replication-message-flags
   #:logical-replication-message-relation-id
   #:logical-replication-message-namespace
   #:logical-replication-message-relation-name
   #:logical-replication-message-replica-identity
   #:logical-replication-message-columns
   #:logical-replication-message-type-oid
   #:logical-replication-message-type-namespace
   #:logical-replication-message-type-name
   #:logical-replication-message-new-tuple
   #:logical-replication-message-old-tuple
   #:logical-replication-message-old-tuple-kind
   #:logical-replication-message-relation-ids
   #:logical-replication-message-options
   #:logical-replication-message-first-segment
   #:logical-replication-message-subtransaction-id
   #:logical-replication-message-abort-lsn
   #:logical-replication-message-abort-time
   #:logical-replication-message-message-lsn
   #:logical-replication-message-prefix
   #:logical-replication-message-content
   #:logical-replication-message-origin-lsn
   #:logical-replication-message-origin-name
   #:logical-replication-message-prepare-lsn
   #:logical-replication-message-prepare-end-lsn
   #:logical-replication-message-prepare-time
   #:logical-replication-message-rollback-end-lsn
   #:logical-replication-message-rollback-time
   #:logical-replication-message-gid
   #:parse-logical-replication-message
   #:logical-replication-unchanged-toast
   #:+logical-replication-unchanged-toast+
   #:logical-replication-unchanged-toast-p
   #:logical-replication-decoder
   #:logical-replication-decoder-p
   #:logical-replication-decoder-type-registry
   #:make-logical-replication-decoder
   #:register-logical-replication-relation
   #:find-logical-replication-relation
   #:forget-logical-replication-relation
   #:clear-logical-replication-relations
   #:decode-logical-replication-tuple
   #:logical-replication-event
   #:logical-replication-event-p
   #:logical-replication-event-kind
   #:logical-replication-event-message
   #:logical-replication-event-relation
   #:logical-replication-event-new-values
   #:logical-replication-event-old-values
   #:logical-replication-event-old-values-kind
   #:decode-logical-replication-message
   #:logical-replication-stream-event
   #:logical-replication-stream-event-p
   #:logical-replication-stream-event-kind
   #:logical-replication-stream-event-replication-message
   #:logical-replication-stream-event-logical-message
   #:logical-replication-stream-event-logical-event
   #:decode-logical-replication-stream-message
   #:logical-replication-read
   #:encode-standby-status-update
   #:encode-hot-standby-feedback
   #:parse-function-call-response
   #:parse-parameter-description
   #:column
   #:column-p
   #:column-name
   #:column-table-oid
   #:column-attribute-number
   #:column-type-oid
   #:column-type-size
   #:column-type-modifier
   #:column-format-code
   #:backend-message-kind
   ;; Crypto helpers useful for authentication integrations and tests
   #:md5-digest
   #:sha256-digest
   #:hmac-sha256
   #:scram-hi
   #:octets-to-base64
   #:base64-to-octets
   ;; Transports
   #:transport
   #:transport-open
   #:transport-close
   #:transport-read-exactly
   #:transport-read-available
   #:transport-wait-readable
   #:transport-write-all
   #:transport-flush
   #:transport-alive-p
   #:transport-start-tls
   #:transport-gss-available-p
   #:transport-start-gss
   #:transport-channel-binding-data
   #:transport-opened-p
   #:socket-transport
   #:socket-transport-tls-options
   #:make-socket-transport
   #:memory-transport
   #:make-memory-transport
   #:memory-transport-input
   #:memory-transport-output
   #:memory-transport-on-write
   #:memory-transport-append-input
   ;; Types
   #:type-codec
   #:make-type-codec
   #:type-codec-oid
   #:type-codec-name
   #:type-codec-text-decoder
   #:type-codec-text-encoder
   #:type-codec-binary-decoder
   #:type-codec-binary-encoder
   #:make-type-registry
   #:type-registry-p
   #:default-type-registry
   #:register-type
   #:register-array-type
   #:register-enum-type
   #:register-domain-type
   #:register-range-type
   #:register-multirange-type
   #:register-composite-type
   #:find-type-codec
   #:decode-value
   #:encode-value
   #:parse-replication-lsn
   #:format-replication-lsn
   #:typed-value
   #:typed-value-p
   #:make-typed-value
   #:typed-value-value
   #:typed-value-type-oid
   #:typed-value-format
   #:json-value
   #:json-value-p
   #:make-json-value
   #:json-value-value
   #:bytea-value
   #:bytea-value-p
   #:make-bytea-value
   #:bytea-value-value
   #:date-value
   #:date-value-p
   #:make-date-value
   #:date-value-value
   #:time-value
   #:time-value-p
   #:make-time-value
   #:time-value-value
   #:timestamp-value
   #:timestamp-value-p
   #:make-timestamp-value
   #:timestamp-value-value
   #:timestamptz-value
   #:timestamptz-value-p
   #:make-timestamptz-value
   #:timestamptz-value-value
   #:interval-value
   #:interval-value-p
   #:make-interval-value
   #:interval-value-value
   #:timetz-value
   #:timetz-value-p
   #:make-timetz-value
   #:timetz-value-value
   #:postgres-interval
   #:postgres-interval-p
   #:make-postgres-interval
   #:postgres-interval-months
   #:postgres-interval-days
   #:postgres-interval-microseconds
   #:postgres-time-with-time-zone
   #:postgres-time-with-time-zone-p
   #:make-postgres-time-with-time-zone
   #:postgres-time-with-time-zone-microseconds
   #:postgres-time-with-time-zone-timezone-seconds
   #:postgres-tid
   #:postgres-tid-p
   #:make-postgres-tid
   #:postgres-tid-block-number
   #:postgres-tid-offset-number
   #:uuid-value
   #:uuid-value-p
   #:make-uuid-value
   #:uuid-value-value
   #:postgres-bit-string
   #:postgres-bit-string-p
   #:make-postgres-bit-string
   #:postgres-bit-string-bits
   #:postgres-bit-string-varying-p
   #:postgres-mac-address
   #:postgres-mac-address-p
   #:make-postgres-mac-address
   #:postgres-mac-address-octets
   #:postgres-inet
   #:postgres-inet-p
   #:make-postgres-inet
   #:postgres-inet-octets
   #:postgres-inet-family
   #:postgres-inet-netmask
   #:postgres-inet-cidr-p
   #:*maximum-numeric-digits*
   #:*maximum-type-registry-catalog-rows*
   #:postgres-array
   #:postgres-array-p
   #:make-postgres-array
   #:postgres-array-elements
   #:postgres-array-dimensions
   #:postgres-array-lower-bounds
   #:postgres-array-element-oid
   #:postgres-range
   #:postgres-range-p
   #:make-postgres-range
   #:postgres-range-lower
   #:postgres-range-upper
   #:postgres-range-lower-inclusive
   #:postgres-range-upper-inclusive
   #:postgres-range-empty-p
   #:postgres-multirange
   #:postgres-multirange-p
   #:make-postgres-multirange
   #:postgres-multirange-ranges
   #:postgres-composite
   #:postgres-composite-p
   #:make-postgres-composite
   #:postgres-composite-fields
   #:postgres-composite-field-names
   #:postgres-composite-field-oids
   #:sql-null
   #:+sql-null+
   #:sql-null-p
   ;; Connection and results
   #:connection
   #:make-connection
   #:parse-connection-string
   #:parse-connection-uri
   #:make-connection-from-string
   #:make-connection-from-uri
   #:connect
   #:connection-open
   #:disconnect
   #:connection-state
   #:connection-host
   #:connection-hostaddr
   #:connection-port
   #:connection-user
   #:connection-database
   #:connection-application-name
   #:connection-startup-parameters
   #:connection-protocol-version
   #:connection-negotiated-protocol-version
   #:connection-password
   #:connection-passfile
   #:connection-oauth-token-provider
   #:connection-oauth-discovery-provider
   #:connection-gss-token-provider
   #:connection-sspi-token-provider
   #:connection-ssl-mode
   #:connection-ssl-negotiation
   #:connection-tls-options
   #:connection-gssenc-mode
   #:connection-gss-service-name
   #:connection-channel-binding
   #:connection-require-auth
   #:connection-target-session-attrs
   #:connection-load-balance-hosts
   #:connection-tls-established-p
   #:connection-gss-established-p
   #:connection-transport
   #:connection-parameters
   #:connection-type-registry
   #:load-type-registry
   #:connection-query-timeout
   #:connection-connect-timeout
   #:connection-backend-process-id
   #:connection-backend-secret-key
   #:connection-backend-pid
   #:connection-backend-secret
   #:connection-transaction-status
   #:connection-logger
   #:connection-metric-registry
   #:connection-notice-handler
   #:connection-notification-handler
   #:connection-max-notifications
   #:connection-notifications
   #:listen
   #:unlisten
   #:unlisten-all
   #:notify
   #:connection-last-result
   #:connection-cancel-transport-factory
   #:connection-healthy-p
   #:cancel-request
   #:poll-notification
   #:wait-for-notification
   #:query-result
   #:query-result-p
   #:result-columns
   #:result-rows
   #:result-command-tag
   #:result-row-count
   #:result-transaction-status
   #:result-notices
   #:result-portal-suspended-p
   #:result-row-alists
   #:row-value
   #:result-row
   #:result-column
   #:result-row-alist
   #:result-rows-as-alists
   #:pipeline-request
   #:pipeline-request-p
   #:pipeline-request-sql
   #:pipeline-request-parameters
   #:pipeline-request-parameter-type-oids
   #:pipeline-request-parameter-formats
   #:pipeline-request-result-formats
   #:pipeline-request-statement-name
   #:pipeline-request-portal-name
   #:make-pipeline-request
   #:query
   #:query-all
   #:query-pipeline
   #:query-pipeline-async
   #:query-async
   #:query-cps
   #:query-pipeline-cps
   #:flush
   #:function-call
   #:prepare
   #:prepared-statement
   #:prepared-statement-p
   #:prepared-statement-name
   #:prepared-statement-sql
   #:prepared-statement-connection
   #:prepared-statement-parameter-type-oids
   #:prepared-statement-columns
   #:cursor
   #:cursor-p
   #:cursor-connection
   #:cursor-statement-name
   #:cursor-portal-name
   #:cursor-fetch-size
   #:cursor-max-result-rows
   #:cursor-max-result-bytes
   #:cursor-columns
   #:cursor-suspended-p
   #:cursor-done-p
   #:cursor-closed-p
   #:cursor-command-tag
   #:open-cursor
   #:cursor-fetch
   #:cursor-close
   #:execute-prepared
   #:close-prepared
   #:begin-transaction
   #:commit-transaction
   #:rollback-transaction
   #:savepoint
   #:release-savepoint
   #:rollback-to-savepoint
   #:with-transaction
   ;; Large objects
   #:large-object
   #:large-object-p
   #:large-object-connection
   #:large-object-oid
   #:large-object-descriptor
   #:large-object-mode
   #:large-object-closed-p
   #:large-object-create
   #:large-object-read-all
   #:large-object-read-range
   #:large-object-from-bytea
   #:large-object-write-at
   #:large-object-import-server-file
   #:large-object-export-server-file
   #:large-object-open
   #:large-object-close
   #:large-object-read
   #:large-object-write
   #:large-object-seek
   #:large-object-tell
   #:large-object-truncate
   #:large-object-unlink
   ;; Pools
   #:connection-pool
   #:make-pool
   #:pool-acquire
   #:pool-release
   #:pool-close
   #:pool-size
   #:pool-available-count
   #:pool-in-use-count
   #:pool-reap
   #:pool-refill
   #:with-connection
   #:pool-max-size
   #:pool-min-size
   #:pool-max-idle-time
   #:pool-max-connection-age
   #:pool-validation-query
   #:pool-connection-factory
   #:pool-closed-p
   ;; COPY
   #:copy-in
   #:copy-out
   #:copy-in-start
   #:copy-in-write
   #:copy-in-write-row
   #:copy-in-write-text-stream
   #:copy-in-write-binary-stream
   #:copy-in-abort
   #:copy-in-finish
   #:copy-out-start
   #:copy-out-read
   #:copy-out-read-all
   #:copy-out-read-rows
   #:copy-both-start
   #:copy-both-write
   #:copy-both-write-row
   #:copy-both-write-text-stream
   #:copy-both-write-binary-stream
   #:copy-both-read
   #:copy-both-read-all
   #:copy-both-read-rows
   #:copy-both-finish
   #:replication-start
   #:replication-read
   #:replication-send-status
   #:replication-send-hot-standby-feedback
   #:replication-finish
   #:replication-identify-system
   #:replication-create-slot
   #:replication-read-slot
   #:replication-drop-slot
   #:replication-alter-slot
   #:replication-show
   #:replication-timeline-history
   #:replication-upload-manifest-start
   #:replication-upload-manifest
   #:replication-base-backup-start
   #:base-backup-start-results
   #:base-backup-read
   #:base-backup-finish
   #:base-backup-final-results
    #:replication-start-physical
    #:replication-start-logical
    #:encode-copy-row
    #:decode-copy-row
    #:encode-copy-text-stream
    #:decode-copy-text-stream
    #:encode-copy-binary-header
    #:encode-copy-binary-trailer
    #:encode-copy-binary-stream
    #:decode-copy-binary-stream
    ;; Authentication limits
   #:*maximum-scram-iterations*))
