(in-package #:cl-postgresql-kit)

(defun %parse-array-text (string)
  (let ((position 0)
        (length (length string))
        (element-count 0))
    (labels ((fail (message)
               (error 'protocol-error :message message :context :array
                      :actual position))
             (check-element-count ()
               (incf element-count)
               (when (> element-count *maximum-array-elements*)
                 (fail "PostgreSQL array has too many elements")))
             (skip-space ()
               (loop while (and (< position length)
                                (find (char string position)
                                      '(#\Space #\Tab #\Newline #\Return #\Page)))
                     do (incf position)))
             (parse-quoted ()
               (unless (and (< position length)
                            (char= (char string position) #\"))
                 (fail "PostgreSQL array quoted value is malformed"))
               (incf position)
               (let ((value
                       (with-output-to-string (stream)
                         (loop
                           (when (>= position length)
                             (fail "PostgreSQL array quoted value is unterminated"))
                           (let ((character (char string position)))
                             (cond ((char= character #\\)
                                    (incf position)
                                    (when (>= position length)
                                      (fail "PostgreSQL array escape is unterminated"))
                                    (write-char (char string position) stream)
                                    (incf position))
                                   ((char= character #\")
                                    (incf position)
                                    (return))
                                   (t
                                    (write-char character stream)
                                    (incf position))))))))
                 (check-element-count)
                 value))
             (parse-unquoted ()
               (let ((start position))
                 (loop while (< position length)
                       for character = (char string position)
                       while (not (or (char= character #\,)
                                      (char= character #\})))
                       do (incf position))
                 (let ((value (string-trim
                               '(#\Space #\Tab #\Newline #\Return #\Page)
                               (subseq string start position))))
                   (when (%sequence-empty-p value)
                     (fail "PostgreSQL array contains an empty unquoted value"))
                   (check-element-count)
                   (if (string= value "NULL") +sql-null+ value))))
             (parse-item (depth)
               (skip-space)
               (when (>= position length)
                 (fail "PostgreSQL array is unterminated"))
               (case (char string position)
                 (#\{ (parse-array (1+ depth)))
                 (#\" (parse-quoted))
                 (otherwise (parse-unquoted))))
             (parse-array (depth)
               (when (> depth *maximum-array-dimensions*)
                 (fail "PostgreSQL array has too many dimensions"))
               (unless (and (< position length)
                            (char= (char string position) #\{))
                 (fail "PostgreSQL array must begin with an opening brace"))
               (incf position)
               (skip-space)
               (if (and (< position length)
                        (char= (char string position) #\}))
                   (progn
                     (incf position)
                     #())
                   (let ((items '()))
                     (loop
                       (push (parse-item depth) items)
                       (skip-space)
                       (cond ((>= position length)
                              (fail "PostgreSQL array is missing its closing brace"))
                             ((char= (char string position) #\,)
                              (incf position)
                              (skip-space))
                             ((char= (char string position) #\})
                              (incf position)
                              (return (coerce (nreverse items) 'vector)))
                             (t
                              (fail "PostgreSQL array has an invalid separator"))))))))
      (skip-space)
      (let ((value (parse-array 1)))
        (skip-space)
        (unless (= position length)
          (fail "PostgreSQL array has trailing data"))
        value))))

(defun %decode-array-node (registry element-oid node)
  (let ((sequence (%array-sequence node)))
    (if sequence
        (let ((result (make-array (length sequence))))
          (loop for index below (length sequence)
                do (setf (aref result index)
                         (%decode-array-node registry element-oid
                                             (aref sequence index))))
          result)
        (if (sql-null-p node)
            +sql-null+
            (decode-value registry element-oid (%encode-utf8 node) :format 0)))))

(defun %decode-array-text (registry element-oid octets)
  (let* ((parsed (%parse-array-text (%decode-utf8 octets)))
         (dimensions (%array-node-dimensions parsed))
         (elements (%decode-array-node registry element-oid parsed)))
    (make-postgres-array :elements elements
                         :dimensions dimensions
                         :lower-bounds (make-array (length dimensions)
                                                   :initial-element 1)
                         :element-oid element-oid)))

(defun %array-text-scalar (registry element-oid value)
  (if (sql-null-p value)
      "NULL"
      (let ((payload (encode-value registry element-oid value :format 0)))
        (let ((string (cond ((stringp payload) payload)
                            ((typep payload '(vector (unsigned-byte 8)))
                             (%decode-utf8 payload))
                            (t (princ-to-string payload)))))
          (with-output-to-string (stream)
            (write-char #\" stream)
            (loop for character across string
                  do (when (or (char= character #\")
                               (char= character #\\))
                       (write-char #\\ stream))
                     (write-char character stream))
            (write-char #\" stream))))))

(defun %write-array-text-node (stream registry element-oid node)
  (let ((sequence (%array-sequence node element-oid)))
    (if sequence
        (progn
          (write-char #\{ stream)
          (loop for index below (length sequence)
                do (when (plusp index) (write-char #\, stream))
                   (%write-array-text-node stream registry element-oid
                                           (aref sequence index)))
          (write-char #\} stream))
        (write-string (%array-text-scalar registry element-oid node) stream))))

(defun %encode-array-text (registry element-oid value)
  (multiple-value-bind (elements dimensions lower-bounds ignored)
      (%array-shape value element-oid)
    (declare (ignore dimensions lower-bounds ignored))
    (%encode-utf8
     (with-output-to-string (stream)
       (%write-array-text-node stream registry element-oid elements)))))
